# Generated by Django 3.2.9 on 2021-11-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('Fname', models.CharField(max_length=20)),
                ('Lname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('contact_no', models.IntegerField(max_length=12)),
                ('pswrd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Seller_info',
            },
        ),
    ]
